name: CI/CD Pipeline with Vercel

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: 7c3afaa8-94a9-4af9-b603-82ec87fd3ae3

    - name: Install dependencies
      run: npm install
    
    - name: Run tests 
      run: npm test

    - name: Deploy to Vercel
      run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm


