name: CI/CD Pipeline with Vercel

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/php@master
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
        SNYK_TOKEN: 7c3afaa8-94a9-4af9-b603-82ec87fd3ae3
      with:
        args: --sarif-file-output=snyk.sarif
          
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif

    - name: Install dependencies
      run: npm install
    
    - name: Run tests 
      run: npm test

    - name: Deploy to Vercel
      run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm


